# Generated by Django 6.0.2 on 2026-02-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='created_at',
        ),
    ]
